/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PianosIndexRouteImport } from './routes/_pianos/index'

const PianosIndexRoute = PianosIndexRouteImport.update({
  id: '/_pianos/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PianosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PianosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pianos/': typeof PianosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_pianos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PianosIndexRoute: typeof PianosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pianos/': {
      id: '/_pianos/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PianosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PianosIndexRoute: PianosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
