/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PianosRouteImport } from './routes/_pianos'
import { Route as PianosNuestraEmpresaIndexRouteImport } from './routes/_pianos/nuestra-empresa/index'
import { Route as PianosGraciasPorContactarIndexRouteImport } from './routes/_pianos/gracias-por-contactar/index'
import { Route as PianosAfinacionIndexRouteImport } from './routes/_pianos/afinacion/index'
import { Route as PianosHomeIndexRouteImport } from './routes/_pianos/_home/index'

const PianosRoute = PianosRouteImport.update({
  id: '/_pianos',
  getParentRoute: () => rootRouteImport,
} as any)
const PianosNuestraEmpresaIndexRoute =
  PianosNuestraEmpresaIndexRouteImport.update({
    id: '/nuestra-empresa/',
    path: '/nuestra-empresa/',
    getParentRoute: () => PianosRoute,
  } as any)
const PianosGraciasPorContactarIndexRoute =
  PianosGraciasPorContactarIndexRouteImport.update({
    id: '/gracias-por-contactar/',
    path: '/gracias-por-contactar/',
    getParentRoute: () => PianosRoute,
  } as any)
const PianosAfinacionIndexRoute = PianosAfinacionIndexRouteImport.update({
  id: '/afinacion/',
  path: '/afinacion/',
  getParentRoute: () => PianosRoute,
} as any)
const PianosHomeIndexRoute = PianosHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => PianosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PianosHomeIndexRoute
  '/afinacion': typeof PianosAfinacionIndexRoute
  '/gracias-por-contactar': typeof PianosGraciasPorContactarIndexRoute
  '/nuestra-empresa': typeof PianosNuestraEmpresaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PianosHomeIndexRoute
  '/afinacion': typeof PianosAfinacionIndexRoute
  '/gracias-por-contactar': typeof PianosGraciasPorContactarIndexRoute
  '/nuestra-empresa': typeof PianosNuestraEmpresaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pianos': typeof PianosRouteWithChildren
  '/_pianos/_home/': typeof PianosHomeIndexRoute
  '/_pianos/afinacion/': typeof PianosAfinacionIndexRoute
  '/_pianos/gracias-por-contactar/': typeof PianosGraciasPorContactarIndexRoute
  '/_pianos/nuestra-empresa/': typeof PianosNuestraEmpresaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/afinacion' | '/gracias-por-contactar' | '/nuestra-empresa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/afinacion' | '/gracias-por-contactar' | '/nuestra-empresa'
  id:
    | '__root__'
    | '/_pianos'
    | '/_pianos/_home/'
    | '/_pianos/afinacion/'
    | '/_pianos/gracias-por-contactar/'
    | '/_pianos/nuestra-empresa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PianosRoute: typeof PianosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pianos': {
      id: '/_pianos'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PianosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pianos/nuestra-empresa/': {
      id: '/_pianos/nuestra-empresa/'
      path: '/nuestra-empresa'
      fullPath: '/nuestra-empresa'
      preLoaderRoute: typeof PianosNuestraEmpresaIndexRouteImport
      parentRoute: typeof PianosRoute
    }
    '/_pianos/gracias-por-contactar/': {
      id: '/_pianos/gracias-por-contactar/'
      path: '/gracias-por-contactar'
      fullPath: '/gracias-por-contactar'
      preLoaderRoute: typeof PianosGraciasPorContactarIndexRouteImport
      parentRoute: typeof PianosRoute
    }
    '/_pianos/afinacion/': {
      id: '/_pianos/afinacion/'
      path: '/afinacion'
      fullPath: '/afinacion'
      preLoaderRoute: typeof PianosAfinacionIndexRouteImport
      parentRoute: typeof PianosRoute
    }
    '/_pianos/_home/': {
      id: '/_pianos/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PianosHomeIndexRouteImport
      parentRoute: typeof PianosRoute
    }
  }
}

interface PianosRouteChildren {
  PianosHomeIndexRoute: typeof PianosHomeIndexRoute
  PianosAfinacionIndexRoute: typeof PianosAfinacionIndexRoute
  PianosGraciasPorContactarIndexRoute: typeof PianosGraciasPorContactarIndexRoute
  PianosNuestraEmpresaIndexRoute: typeof PianosNuestraEmpresaIndexRoute
}

const PianosRouteChildren: PianosRouteChildren = {
  PianosHomeIndexRoute: PianosHomeIndexRoute,
  PianosAfinacionIndexRoute: PianosAfinacionIndexRoute,
  PianosGraciasPorContactarIndexRoute: PianosGraciasPorContactarIndexRoute,
  PianosNuestraEmpresaIndexRoute: PianosNuestraEmpresaIndexRoute,
}

const PianosRouteWithChildren =
  PianosRoute._addFileChildren(PianosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PianosRoute: PianosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
